// AUTO-GENERATED by @lovable.dev/mcp-js — do not edit. Regenerated by the Vite plugin.
// To take ownership, delete this banner line; the plugin then leaves the file alone.
// supabase function: mcp
// Bundled from src/lib/mcp/index.ts by @lovable.dev/mcp-js.
// src/lib/mcp/index.ts
import { defineMcp } from "npm:@lovable.dev/mcp-js@0.25.0";

// src/lib/mcp/tools/get-studio-info.ts
import { defineTool } from "npm:@lovable.dev/mcp-js@0.25.0";
var get_studio_info_default = defineTool({
  name: "get_studio_info",
  title: "Get studio info",
  description: "Returns general information about Creant Studio: what the studio does, location context, and how to get in touch.",
  inputSchema: {},
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: () => {
    const info = {
      name: "Creant Studio",
      tagline: "Estudio creativo de branding, contenido y publicidad digital para pymes.",
      website: "https://estudiocreant.com",
      email: "Creantagency.contacto@gmail.com",
      whatsapp: "https://wa.link/yzax1m",
      instagram: "https://www.instagram.com/estudio.creant/",
      tiktok: "https://www.tiktok.com/@creantagency",
      description: "Combinamos branding, identidad visual, contenido UGC y campa\xF1as de performance (Meta & Google Ads) para que las pymes crezcan de forma medible."
    };
    return {
      content: [{ type: "text", text: JSON.stringify(info, null, 2) }],
      structuredContent: info
    };
  }
});

// src/lib/mcp/tools/list-services.ts
import { defineTool as defineTool2 } from "npm:@lovable.dev/mcp-js@0.25.0";
var services = [
  {
    id: "strategic-design",
    name: "Dise\xF1o Estrat\xE9gico",
    description: "Identidad visual, branding y dise\xF1o de interfaces pensadas para convertir y destacar en el mercado."
  },
  {
    id: "growth-marketing",
    name: "Marketing de Crecimiento",
    description: "Estrategias integrales, gesti\xF3n de redes y campa\xF1as enfocadas en el retorno de inversi\xF3n y escalabilidad."
  },
  {
    id: "performance-ads",
    name: "Performance Ads",
    description: "Campa\xF1as publicitarias optimizadas con datos reales para adquirir clientes calificados constantemente."
  }
];
var list_services_default = defineTool2({
  name: "list_services",
  title: "List services",
  description: "List the services Creant Studio offers, with a short description of each.",
  inputSchema: {},
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: () => ({
    content: [{ type: "text", text: JSON.stringify(services, null, 2) }],
    structuredContent: { services }
  })
});

// src/lib/mcp/tools/list-team.ts
import { defineTool as defineTool3 } from "npm:@lovable.dev/mcp-js@0.25.0";
var team = [
  {
    name: "Milagros",
    role: "Co-Founder & Creative Director",
    experienceYears: 6,
    bio: "Especialista en branding, identidad visual, comunicaci\xF3n, edici\xF3n de video y contenido UGC.",
    skills: ["Branding", "Identidad Visual", "Video / UGC", "Comunicaci\xF3n"]
  },
  {
    name: "Juan",
    role: "Co-Founder & Growth Strategist",
    experienceYears: 5,
    bio: "Ads y Social Media Manager. Especialista en performance, email marketing y estrategias de ventas.",
    skills: ["Meta & Google Ads", "Social Media", "Email Marketing", "Ventas"]
  }
];
var list_team_default = defineTool3({
  name: "list_team",
  title: "List team",
  description: "List the founders of Creant Studio with their role, experience, and skills.",
  inputSchema: {},
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: () => ({
    content: [{ type: "text", text: JSON.stringify(team, null, 2) }],
    structuredContent: { team }
  })
});

// src/lib/mcp/tools/request-contact.ts
import { defineTool as defineTool4 } from "npm:@lovable.dev/mcp-js@0.25.0";
import { z } from "npm:zod@^3.25.76";
var request_contact_default = defineTool4({
  name: "request_contact",
  title: "Request contact",
  description: "Prepare a prefilled contact message for Creant Studio. Returns the studio's email and a prefilled WhatsApp link the user can open to start the conversation. Does not send anything on its own.",
  inputSchema: {
    name: z.string().min(1).describe("Name of the person or company reaching out."),
    message: z.string().min(1).describe("Short description of the project or need."),
    email: z.string().email().optional().describe("Optional reply-to email.")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: true },
  handler: ({ name, message, email }) => {
    const waText = `Hola Creant! Soy ${name}.
${message}` + (email ? `
Email: ${email}` : "");
    const whatsappUrl = "https://wa.me/?text=" + encodeURIComponent(waText);
    const mailtoUrl = `mailto:Creantagency.contacto@gmail.com?subject=${encodeURIComponent(`Nuevo contacto - ${name}`)}&body=${encodeURIComponent(message + (email ? `

Email: ${email}` : ""))}`;
    const result = {
      instructions: "Abr\xED uno de los links para iniciar la conversaci\xF3n con Creant Studio. Nada se env\xEDa autom\xE1ticamente.",
      whatsappUrl,
      mailtoUrl,
      email: "Creantagency.contacto@gmail.com"
    };
    return {
      content: [{ type: "text", text: JSON.stringify(result, null, 2) }],
      structuredContent: result
    };
  }
});

// src/lib/mcp/index.ts
var mcp_default = defineMcp({
  name: "creant-studio-mcp",
  title: "Creant Studio",
  version: "0.1.0",
  instructions: "Public MCP server for Creant Studio (estudiocreant.com). Use these tools to fetch information about the studio's services, team, and contact channels, or to prepare a contact message. All data is public and no authentication is required.",
  tools: [get_studio_info_default, list_services_default, list_team_default, request_contact_default]
});

// lovable-mcp-supabase-entry.ts
import { createSupabaseHandler } from "npm:@lovable.dev/mcp-js@0.25.0/stacks/supabase";
Deno.serve(createSupabaseHandler(mcp_default, { functionName: "mcp" }));
